defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: aquila3d/aquila3d-ci
  environment:
    TERM: dumb

branches:
  ignore:
    - gh-pages
    - docker

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build
          command: |
            echo "org.gradle.parallel=false" >> gradle.properties
            ./gradlew build --no-daemon --stacktrace
